models/node.py
import time
from . import ModelMixin
from . import db


class Node(db.Model, ModelMixin):
    __tablename__ = 'nodes'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String())
    description = db.Column(db.String())
    created_time = db.Column(db.String(), default=0)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    topics = db.relationship('Topic', backref="node")

    def __init__(self, form):
        format = '%Y/%m/%d %H:%M:%S'
        v = int(time.time()) + 3600 * 8
        valuegmt = time.gmtime(v)
        dt = time.strftime(format, valuegmt)
        self.name = form.get('name', '')
        self.description = form.get('description')
        self.created_time = dt
        # self.user_id = current_user.id


    def update(self, form):
        self.name = form.get('node_name', '')
        self.save()

models/topic.py
import time
from . import ModelMixin
from . import db
from . import timestamp
# from routes.user import current_user


class Topic(db.Model, ModelMixin):
    __tablename__ = 'topics'
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100))
    content = db.Column(db.String(1000))
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    node_id = db.Column(db.Integer, db.ForeignKey('nodes.id'))
    created_time = db.Column(db.String(), default=0)

    # has relationship with comments
    comments = db.relationship('Comment', backref="topic")

    def __init__(self, form):
        format = '%Y/%m/%d %H:%M:%S'
        v = int(time.time()) + 3600 * 8
        valuegmt = time.gmtime(v)
        dt = time.strftime(format, valuegmt)
        self.created_time = dt
        self.title = form.get('title', '')
        self.content = form.get('content', '')
        # self.user_id = current_user.id


    def update(self, form):
        self.title = form.get('topic_title', '')
        self.title = form.get('topic_content', '')
        self.save()

routes/comment.py
from models.comment import Comment
from routes import *
from routes.user import current_user

main = Blueprint('comment', __name__)

Model = Comment

@main.app_context_processor
def inject_permissions():
    return dict(u=current_user)

@main.route('/add', methods=['POST'])
def add():
    print('comment add was called')
    form = request.form
    m = Model(form)
    m.topic_id = int(form.get('topic_id'))
    m.save()
    return redirect(url_for('topic.show', id=m.topic_id))

routes/node.py
from models.node import Node
from models.user import User
from models.topic import Topic
from routes import *
from routes.user import current_user

# for decorators
from functools import wraps


main = Blueprint('node', __name__)

Model = Node

# def current_node():
#     nid = session.get('node_id')
#     if nid is not None:
#         n = Node.query.get(nid)
#         return n


def admin_required(f):
    @wraps(f)
    def function(*args, **kwargs):
        # your code
        print('admin required')
        u = current_user()
        if u.is_administrator:
            print('current user is administrator')
        else:
            print('current user is not administrator')
            abort(410)
        # if request.args.get('uid') != '1':
        #     print('not admin')
        #     abort(404)
        # return f(*args, **kwargs)
    return function


@main.route('/')
def index():
    print('执行到node根目录')
    ms = Model.query.all()
    # print('ms:', ms)
    return render_template('node_index.html', node_list=ms)

# @main.route('/show')
# def show():
#     print('执行到node根目录')
#     ms = Model.query.all()
#
#     node = Node.query.first()
#     # print('ms:', ms)
#     return render_template('node_all.html', node_list=ms,node=node)

@main.route('/show')
def show():
    print('执行到node/show目录')
    # u = current_user()
    # print('node.show根目录下：u.is_administrator', u.is_administrator)
    ms = Model.query.all()
    node = Node.query.first()
    return render_template('node_all.html', node_list=ms, node=node)

@main.route('/new', methods=['GET', 'POST'])
def new():
    print('node.new was called')
    u = current_user()
    print('u.is_administrator', u.is_administrator)
    if u.is_administrator:
        print('current user is administrator')
    else:
        print('current user is not administrator')
        abort(410)
    return render_template('node_new.html')


@main.route('/showSinglePage/<int:id>')
def showSinglePage(id):
    nodes = Model.query.all()
    node = Model.query.get(id)
    print('node',node)
    # username = node.user.username
    # print('username', username)
    return render_template('node_all.html', node_list=nodes, node=node)


@main.route('/showAllPages')
def showAllPages():
    nodes = Node.query.all()
    return render_template('node_all.html', nodes=nodes)



@main.route('/edit/<id>')
def edit(id):
    n = Model.query.get(id)
    return render_template('node_edit.html', node=n)


@main.route('/add', methods=['POST'])
def add():
    print('node add was called')
    form = request.form
    m = Model(form)
    u = current_user()
    m.user_id = u.id
    m.save()
    return redirect(url_for('.index'))


@main.route('/update/<int:id>', methods=['POST'])
def update(id):
    form = request.form
    n = Model.query.get(id)
    n.update(form)
    return redirect(url_for('.index'))


@main.route('/delete/<int:id>')
# @admin_required
def delete(id):
    t = Model.query.get(id)
    t.delete()
    return redirect(url_for('.index'))

routes/topic.py
from models.topic import Topic
from models.node import Node
from routes import *
from routes.user import current_user

main = Blueprint('topic', __name__)

Model = Topic

@main.app_context_processor
def inject_permissions():
    return dict(u=current_user)


@main.route('/<int:id>')
def index(id):
    # ms = Model.query.all()
    m = Model.query.get(id)
    # node = Node.query.get(m.node_id)
    return render_template('topic_index.html', topic=m)


@main.route('/new')
def new():
    u = current_user()
    if u is not None:
        return render_template('topic_new.html')
    else:
        return redirect(url_for('user.login_view'))
    # return render_template('topic_new.html', u=u)


@main.route('/<int:id>')
def show(id):
    print('topic.show was called')
    ts = Model.query.all()
    # t = Model.query.get(id)
    # 有了关系之后关联的字段就不必要给出来了
    # node = Node.query.get(t.node_id)
    return render_template('topic.html', topic_list=ts)

# @main.route('/')
# def show():
#     print('topic.show was called')
#     ts = Model.query.all()
#     # t = Model.query.get(id)
#     # 有了关系之后关联的字段就不必要给出来了
#     # node = Node.query.get(t.node_id)
#     return render_template('topic.html', topic_list=ts)

@main.route('/edit/<id>')
def edit(id):
    t = Model.query.get(id)
    return render_template('topic_edit.html', topic=t)


@main.route('/add', methods=['POST'])
def add():
    print('topic.add was called')
    form = request.form
    t = Model(form)
    u = current_user()
    t.node_id = int(form.get('node_id'))
    t.user_id = u.id
    t.save()
    print('topic',t)
    return redirect(url_for('.index', id=t.id))


@main.route('/comment/add', methods=['POST'])
def comment_add():
    form = request.form
    m = Model(form)
    m.save()
    return redirect(url_for('topic.index'))


@main.route('/update/<int:id>', methods=['POST'])
def update(id):
    form = request.form
    t = Model.query.get(id)
    t.update(form)
    return redirect(url_for('.index', id=id))

templates/410.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="/static/css/pure-min.css">
    <link rel="stylesheet" href="/static/css/main.css">
    <script src="/static/js/jquery-3.0.0.min.js"></script>
    <script type="text/javascript" src="/static/js/weibo.js"></script>
    <title>阿荷和她的朋友们</title>
</head>
<body>
  <h1>用户名已存在！</h1>
</body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>

    <link rel="stylesheet" href="{{ url_for('static', filename='css/bbs.css') }}">
    <link rel="stylesheet" href="/static/css/pure-min.css">
    <link rel="stylesheet" href="/static/css/main.css">
    <link rel="stylesheet" href="/static/css/bbs.css">
    {% block css %}{% endblock %}

    <script src="/static/js/jquery-3.0.0.min.js"></script>
    {% block script %}{% endblock %}
</head>
<body>
    <div class="bbs-top">
        <a class="gua-nav-link" href="/node/show">首页</a>
        <input type="text" class="bbs-icon-input">
        <nav class="bbs-menu">
            <a class="gua-nav-link gua-active" href="/user/profile">个人主页</a>
            <a class="gua-nav-link" href="/user">注册</a>
            <a class="gua-nav-link" href="/user">登录</a>
            <a class="gua-nav-link" href="/blog">博客</a>
            <a class="gua-nav-link" href="/weibo">微博</a>
            <a class="gua-nav-link" href="/user/logout">登出</a>
            <!--<a class="gua-nav-link" href="/weibo">微博</a>-->
        </nav>
    </div>
    <div class="bbs-main">
        <div class="bbs-content bbs-box">
            {% block content %}
            {% endblock %}
        </div>
        <div class="bbs-sidebar bbs-box">
            <!--<a href="/topic/new">发布新话题</a>-->
            <!--<div class="bbs-box bbs-sidebar">-->
                <div class="bbs-sidebar-container">
                    <div class="bbs-sidebar-user">
                        <!--<img class="bbs-user-avatar"  src="/static/img/sen.jpg">-->
                        {% if u() %}
                        <a class="bbs-user-name" href="/user/profile">
                            {{ u().username }}
                        </a>
                        {% else %}
                            哈喽，游客！
                        {% endif %}
                    </div>
                    <div class="he-line-h">

                    </div>
                    <div class="bbs-favorite-container">
                        <div class="bbs-favorite">
                            <div class="bbs-text-default">
                                <a>0</a>
                            </div>
                            <div class="bbs-text-default">
                                <a>节点收藏</a>
                            </div>
                        </div>
                        <div class="he-line-v">
                        </div>
                        <div class="bbs-favorite">
                            <div class="bbs-text-default">
                                <a>0</a>
                            </div>
                            <div class="bbs-text-default">
                                <a>主题收藏</a>
                            </div>
                        </div>
                        <div class="he-line-v">
                        </div>
                        <div class="bbs-favorite">
                            <div class="bbs-text-default">
                                <a>0</a>
                            </div>
                            <div class="bbs-text-default">
                                <a>特别关注</a>
                            </div>
                        </div>
                        <!--<div class="bbs-line1"></div>-->
                        <!--<div class="bbs-favorite">-->
                            <!--<p class="bbs-text-default">0</p>-->
                            <!--<a class="bbs-text-default" href="#">主题收藏</a>-->
                        <!--</div>-->
                        <!--<div class="bbs-line1"></div>-->
                        <!--<div class="bbs-favorite">-->
                            <!--<p class="bbs-text-default">0</p>-->
                            <!--<a class="bbs-text-default" href="#">特别关注</a>-->
                        <!--</div>-->
                    </div>
                    <div class="he-line-h">

                    </div>
                </div>
                <div class="bbs-sidebar-cell">
                    <div class="bbs-line2"></div>
                </div>
                <div class="bbs-sidebar-cell">
                    <img class="bbs-add" src="/static/img/add.png">
                    <a class="bbs-a-gray1" href="/topic/new">创作新主题</a>
                </div>
                <div class="bbs-sidebar-cell">
                    {% if u().is_administrator %}
                    <img class="bbs-add" src="/static/img/add.png">
                    <a class="bbs-a-gray1" href="/node/new">
                        开启新版块
                    </a>
                    {% endif %}
                </div>
                <div class="bbs-sidebar-cell">
                    <a class="bbs-a-gray1" href="#">0 条未读提醒</a>
                </div>
</div>
            {% block sidebar %}
            {% endblock %}
        </div>
    </div>

    <div class="bbs-bottom">
        <div class="bbs-bottom-content bbs-content-size">
            <div class="bbs-bottom-nav">
                <a href="#">关于</a>
                <span>&nbsp;·&nbsp;</span>
                <a href="#">FAQ</a>
                <span>&nbsp;·&nbsp;</span>
                <a href="#">鸣谢</a>
                <span>&nbsp;·&nbsp;</span>
                <a href="#">7人在线</a>
            </div>
            <div class="bbs-bottom-about">
                创意工作者们的社区<br>World is powered by solitude
            </div>
        </div>
    </div>
</body>
</html>

templates/blog_add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="/static/css/pure-min.css">
    <link rel="stylesheet" href="/static/css/main.css">
    <script src="/static/js/jquery-3.1.0.min.js"></script>
    <scrit type="text/javascript" src="/static/js/weibo.js"></scrit>
    <title>阿荷和她的朋友们</title>
</head>
<body>
  <div class="head">
    <div class="left title">阿荷和她的朋友们</div>
    <div class="right">
      <span><a href="/blog">阿荷的博客</a></span>
      <span><a href="/weibo">微博</a></span>
      <span><a href="/profile">个人资料</a></span>
    </div>
  </div>
  <div class="background">
    <div class="height-20"></div>
    <div class="container clearfix">

      <div class="right-panel right">
        <div class="box name-board">
          <img class="avatar-l name-board-avatar" src="/static/img/sen.jpg" alt="" />
          <div class="personal-des">
            Hello, I am ahe
          </div>
          <div class="personal-des">
            Welcome here
          </div>
          <div class="personal-des">
            Please write some comments
          </div>
          <div class="personal-des">
            Have a nice day!
          </div>
        </div>
        <div class="height-20"></div>
        <div class="box link-board">
          <pre class="poem">
Down by the salley gardens
My love and I did meet
She passed the salley gardens
With little snow-white feet
She bid me take love easy
As the leaves grow on the tree
But I being young and foolish
With her would not agree
In a field by the river
My love and I did stand
And on my leaning shoulder
She laid her snow-white hand
She bid me take life easy
As the grass grows on the weirs
But I was young and foolish
And now I'm full of tears
Down by the salley gardens
My love and I did meet
She passed the salley gardens
With little snow-white feet
She bid me take love easy
As the leaves grow on the tree
But I being young and foolish
With her would not agree
          </pre>
        </div>
      </div>



      <div class="main-panel">

        <div class="box add-box">
          <form action="/blog/add" method="post" class="out">
            <input name="title" class="wei" placeholder="Title"> </input>
            <textarea name="content" class="wei" placeholder="Blog" rows="10"> </textarea>
            <button class="pure-button pure-button-primary sub" type="submit">发布博客</button>
          </form>
        </div>
        <div class="height-20"></div>

        <div class="box">
          {% for b in blogs %}
            <div class="cell item">
              <div class="">
                {{ b.title }}
              </div>
              <pre class="">{{ b.content }}</pre>
            </div>
          {% endfor %}
        </div>
        <div class="height-20"></div>

      </div>



    </div>
  </div>
</body>
</html>

templates/blog_index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="/static/css/pure-min.css">
    <link rel="stylesheet" href="/static/css/main.css">
    <!--<script src="https://code.jquery.com/jquery-3.1.0.min.js" integrity="sha256-cCueBR6CsyA4/9szpPfrX3s49M9vUU5BgtiJj06wt/s=" crossorigin="anonymous"></script>-->
    <script src="/static/js/jquery-3.0.0.min.js"></script>
    <script src="/static/js/api.js"></script>
    <script type="text/javascript" src="/static/js/blog.js"></script>
    <title>阿荷和她的朋友们</title>
</head>
<body>
  <div class="head">
    <div class="left title">this is blog_index.html 阿荷的朋友圈</div>
    <div class="right">
      <span><a class="gua-nav-link" href="/node/show">首页</a></span>
         <span><a class="gua-nav-link gua-active" href="/user/profile">个人主页</a></span>
         <span><a class="gua-nav-link" href="/user">注册</a></span>
         <span><a class="gua-nav-link" href="/user">登录</a></span>
         <span><a class="gua-nav-link" href="/blog">博客</a></span>
         <span><a class="gua-nav-link" href="/weibo">微博</a></span>
    </div>
  </div>
  <div class="background">
    <div class="height-20"></div>
    <div class="container clearfix">

      <div class="right-panel right">
        <div class="box name-board">
          <img class="avatar-l name-board-avatar" src="/static/img/sen.jpg" alt="" />
          <div class="personal-des">
            Hello, I am ahe
          </div>
          <div class="personal-des">
            Welcome here
          </div>
          <div class="personal-des">
            Please write some comments
          </div>
          <div class="personal-des">
            Have a nice day!
          </div>
          {% if u().is_administrator %}
          <div class="personal-des">
            <span><a class="gua-nav-link" href="/blog/new">发布新博客</a></span>
          </div>
          {% endif %}
        </div>
        <div class="height-20"></div>
        <div class="box link-board">
          <pre class="poem">
Down by the salley gardens
My love and I did meet
She passed the salley gardens
With little snow-white feet
She bid me take love easy
As the leaves grow on the tree
But I being young and foolish
With her would not agree
In a field by the river
My love and I did stand

          </pre>
        </div>
      </div>



      <div class="main-panel">

        <div class="box">
          {% for b in blogs %}
            <div class="cell item">
              <div class="blog-head">
                <span class="blog-title">{{ b.title }}</span>
                <span class="blog-name">by:{{ u().username }}</span>
                <span class="blog-time">{{ b.created_time }}</span>
              </div>
              <pre class="blog-content">{{ b.content }}</pre>
              <div class="blog-foot">
                <a href="#" class="blog-com">评论({{ b.comments_num }})</a>
              </div>
              <div class="blog-comment hide">
                <div class="comment-list">
                {% for c in b.comments %}
                  <div class="cell-inner item">
                    <span class="comment">{{ c.comment }}</span>
                    <span class="right  span-margin">{{ c.created_time }}</span>&nbsp;&nbsp;
                    <span class="right  span-margin">by:{{ c.name }}</span>
                    <!--<span class="time right span-margin">{{ c.created_time }}</span>-->
                    <!--<span class="name right span-margin">by:{{ c.name }}</span>-->
                  </div>
                {% endfor %}
                </div>
                <!-- <form action="/blog/comment" method="post" class="comment-form"> -->
                <div class="comment-form">
                  <input type="hidden" name="blog_id" class="comment-blog_id" value="{{ b.id }}">
                  <input name="comment" class="left m comment-content" placeholder="Comment">
                  <button class="blog-comment-add">发表</button>
                </div>
                <!-- </form> -->
              </div>
            </div>
          {% endfor %}
        </div>
        <div class="height-20"></div>

      </div>



    </div>
  </div>
</body>
</html>

templates/node_all.html
{% extends "base.html" %}

{% block title %}
    发帖


{% endblock %}
{% block css %}
<style>
    .he-line-h {
      height: 1px;
      background: lightgray;
      margin: 15px 5px;
    }

   .bbs-nodes {
        height: 60px;
        line-height:60px;
        padding: 5px;
        font-size: 20px;
        font-style: initial;
        font-family: cursive;
        border: thin solid lightgray;
        border-radius: 10px;
        margin-bottom: 5px;
    }

   .bbs-titles {
        font-family: -webkit-pictograph;
        font-size: 20px;
        font-style: inherit;
        border: thin solid lightgray;
        border-radius: 10px;
    }

   .bbs-title{
        height: 30px;
        padding:5px;
        border-top: black solid thin;

   }
   .cell {
      padding: 10px;
      line-height: 120%;
      border-bottom: 1px solid #e2e2e2;
}

</style>
{% endblock %}

{% block script %}

{% endblock %}


{% block content %}
    <div class="bbs-nodes">
        {% for node in node_list %}
            <a href="{{ url_for('node.showSinglePage', id=node.id)}}" >{{ node.name }}</a>&nbsp;&nbsp;
             <!--<a href="{{ url_for('node.show', id=node.id)}}" >{{ node.name }}</a>&nbsp;&nbsp;-->

        {% endfor %}
    </div>
    <div class="bbs-titles cell">
    {% for t in node.topics %}
        <div class="bbs-title">
            <a href="{{ url_for('topic.show', id=t.id)}}">{{ t.title }}</a>
            <span class="right span-margin">@{{ t.created_time }}</span>
            <span class="right span-margin">created by: {{ t.user.username }}</span>
        </div>
    {% endfor %}
    </div>
{% endblock %}

templates/node_edit.html
{% extends "base.html" %}

{% block title %}
    编辑新的板块
{% endblock %}

{% block content %}
this is node_new.html
    <form action="{{ url_for('.update', id=node.id) }}" method="post">
        <input type="text" name="node_name" value="{{ node.name }}">
        <button class="pure-button pure-button-primary sub">更新</button>
    </form>
{% endblock %}


{% block sidebar %}
    <h1>hello </h1>
    <a href="/node/new">发布新帖子</a>
{% endblock %}

templates/node_new.html
{% extends "base.html" %}

{% block title %}
    发布新的板块
{% endblock %}

{% block content %}
this is node_new.html
    <form action="{{ url_for('.add') }}" method="post">
        <div class="cell">输入板块名：<br>
        <input type="text" name="name" placeholder="输入 title">
        </div>
        <div>
            <p>请输入对板块的描述：</p>
            <textarea cols="60" rows="10" type="text" name="description" placeholder="输入 description"></textarea>
        </div>

        <button class="pure-button pure-button-primary sub">Add</button>
    </form>
{% endblock %}

templates/todo_edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>todo edit</title>
</head>
<body>
    <div>
        <!-- action="/todo/update/{{todo.id}}" -->
        <form action="{{ url_for('.update', id=todo.id) }}" method="post">
            <input type="text" name="task" value="{{ todo.task }}">
            <button>更新</button>
        </form>
    </div>
</body>
</html>

templates/todo_index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>todo</title>
    <style>
        form {
            display: inline-block;
        }
    </style>
</head>
<body>
    <div>
        <form action="{{ url_for('.add') }}" method="post">
            <input type="text" name="task" placeholder="输入 todo">
            <button>Add</button>
        </form>
    </div>

{% for todo in todo_list %}
    <div>
        <a href="{{ url_for('.edit', id=todo.id) }}">修改</a>
        <a href="{{ url_for('.delete', id=todo.id) }}">删除</a>
        {{ todo.task }}
    </div>
{% endfor %}

</body>
</html>

templates/topic_index.html
{% extends "base.html" %}

{% block title %}

{% endblock %}
{% block css %}
<style>
    .cell {
        padding: 10px;
        font-size: 12px;
        line-height: 120%;
        text-align: left;
        border-bottom: 1px solid #e2e2e2;
    }
    .msl {
    width: 100%;
    border: none;
    resize: none;
    background-color: #f9f9f9;
    outline: none;
    font-size: 14px;
    line-height: 20px;
    padding: 10px;
    font-family: 'Helvetica Neue', 'Hiragino Sans GB', 'Microsoft Yahei', sans-serif;
    margin: 0px;
    box-sizing: border-box;
}

.normal.button {
    background-color: #f9f9f9;
    border: 1px solid rgba(60,60,70,0.3);
    color: #333;
    text-shadow: 0px 1px 0px #fff;
    text-decoration: none;
    font-weight: bold;
    cursor: pointer;
    box-shadow: 0px 1px 0px rgba(66, 66, 77, 0.1);
}
.bbs-topic-content{
    font-size: 20px;
    line-height: 1.5em;
    padding: 0 20px;
}

</style>
{% endblock %}

{% block script %}

{% endblock %}



{% block content %}
this is topic_index.html
<br>
    所属板块：{{ topic.node.name }}<br>
    <div class="cell">
    标题：
    </div>
    <h4>{{ topic.title }}</h4>
    <div class="right">
            by 话题发布者：   {{ topic.user.username }}
            <a href="{{ url_for('.edit', id=topic.id) }}">修改</a>
    </div>
    <div class="cell">
    内容：
    </div>
    <div class="bbs-topic-content">
        <p>{{ topic.content }}</p>

    </div>
    <div class="cell">
    评论如下：
    </div>
    <div class="cell-inner item">
        {% for c in topic.comments %}
            {{ c.content }}
        <div class="right">
            commented by {{ u().username }}@ {{ c.created_time }}
        </div>
        {% endfor %}
    </div>
    <div>
        <form action="{{ url_for('comment.add') }}" method="post">
            <input type="hidden" name="topic_id" value="{{ topic.id }}">
            <textarea cols="80" rows="3" name="content"></textarea><br>
            <button class="normal button">发表回复</button>
        </form>
    </div>
{% endblock %}

templates/topic_new.html
{% extends "base.html" %}

{% block title %}
    发布新话题
{% endblock %}

{% block css %}
<style>
    .cell {
        padding: 10px;
        font-size: 12px;
        line-height: 120%;
        text-align: left;
        border-bottom: 1px solid #e2e2e2;
    }
    .msl {
    width: 100%;
    border: none;
    resize: none;
    background-color: #f9f9f9;
    outline: none;
    font-size: 14px;
    line-height: 20px;
    padding: 10px;
    font-family: 'Helvetica Neue', 'Hiragino Sans GB', 'Microsoft Yahei', sans-serif;
    margin: 0px;
    box-sizing: border-box;
}
</style>
{% endblock %}

{% block script %}

{% endblock %}





{% block content %}
this is topic_new.html 请输入选择的版块
    <form action="{{ url_for('.add') }}" method="post">
        <input type="text" name="node_id" placeholder="输入 node id">
        <br>
        <div class="cell">
        主题标题
        </div>
        <!--<input type="text" name="title" placeholder="输入 title">-->
        <textarea class="msl" rows="1" maxlength="120" id="topic_title" name="title" autofocus="autofocus" placeholder="请输入主题标题，如果标题能够表达完整内容，则正文可以为空"></textarea>
        <br>
        <div class="cell">
        正文
        </div>
        <textarea cols="90" rows="10" type="text" name="content" placeholder="输入 content"></textarea>
        <br>
        <button class="pure-button pure-button-primary sub">发布主题</button>
    </form>
{% endblock %}

templates/user_login.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="/static/css/login.css">
    <title>Hello ahe</title>
  </head>
  <body>
  <div class="he-container">
      <div class="loginform">
          <h1>已有登陆帐号</h1>
            <ul>
              <form action="{{ url_for('.login') }}" method="post">
                <li class="inputfont"><input type="text" class="input" name="username" placeholder="已注册网站通行证"></li>
                <li class="inputfont"><input type="password" class="input" name="password" placeholder="密码"></li>
                <li><a class="reg" href="{{ url_for('.register_view') }}">免费注册</a></li>
                <li><input type="submit" class="gua-button-big" value="登 陆"></li>
              </form>
            </ul>
        </div>
      </div>
    </div>
  </div>
  </body>
</html>

templates/user_register.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="/static/css/login.css">
    <title>Hello ahe</title>
  </head>
  <body>
  <div class="he-container">
    	<div class="block">
        	<div class="loginform">
            	<h1>注册帐号</h1>
                <ul>
                    <form action="{{ url_for('.register') }}" method="post">
                	<li class="inputfont"><input type="text" class="input" name="username" placeholder="用户名"></li>
                    <li class="inputfont"><input type="password" class="input" name="password" placeholder="密码"></li>
                    <li><input type="submit" class="gua-button-big" value="注 册"></li>
                    </form>
                </ul>
            </div>
        </div>
</div>

  </body>
</html>